# Generated by Django 4.0.2 on 2022-02-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to='image/brand/%y/%m/%d', width_field=400),
        ),
    ]
