# Generated by Django 4.0.1 on 2022-01-29 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Descreption', models.TextField(default='not found')),
                ('Exipir_data', models.DateField(default=datetime.datetime.now)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
        ),
    ]
