# Generated by Django 4.0.1 on 2022-02-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.IntegerField(default=0)),
                ('type_name', models.CharField(default='no Type', help_text='Enter type name ', max_length=20)),
            ],
        ),
    ]
