# Generated by Django 4.0.1 on 2022-02-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='id_type',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type'),
        ),
    ]
