# Generated by Django 4.0.1 on 2022-02-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_type_id_type_alter_products_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Descreption',
        ),
    ]
