# Generated by Django 4.0.1 on 2022-02-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_descreption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='name',
        ),
    ]
