# Generated by Django 4.0.1 on 2022-02-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_type_name_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_type',
            new_name='type',
        ),
    ]
