# Generated by Django 4.0.2 on 2022-02-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_product_type_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='crate_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
