# Generated by Django 4.0.2 on 2022-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Descreption',
            field=models.TextField(default='', max_length=200),
        ),
    ]
