# Generated by Django 4.0.2 on 2022-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_descreption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='image/products/wk21_brushes_02.jpg', null=True, upload_to='image/products/%y/%m/%d'),
        ),
    ]
