# Generated by Django 4.0.1 on 2022-01-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_products_descreption_products_exipir_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
