# Generated by Django 4.0.1 on 2022-01-30 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makeup', '0003_remove_products_brand_delete_brand_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='connect_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Enter topic', max_length=30)),
                ('massesg', models.TextField(help_text='Enter massesg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
